language: c
os:
  - linux
  - osx
dist: trusty
notifications:
  email: false
script:
  - if [ $(uname) = Linux ]; then
      sudo apt-get install -y doxygen;
      tools/gyp/gyp --depth=. utf8rewind.gyp;
      make -j4;
      make -j4 tests-rewind;
    fi
  - if [ $(uname) = Darwin ]; then
      brew install doxygen;
      tools/gyp/gyp --depth utf8rewind.gyp;
      xcodebuild;
    fi
  - echo ok | output/*/x86/Debug/tests-rewind
