language: c
os:
  - linux
  - osx
dist: trusty
osx_image: xcode7.3
script:
  - if [ $(uname) = Linux ]; then sudo apt-get install -y doxygen; fi
  - if [ $(uname) = Darwin ]; then brew install doxygen; fi
  - tools/gyp/gyp --depth=. --format=make utf8rewind.gyp
  - make -j4
  - make -j4 tests-rewind
  - echo ok | output/*/x86/Debug/tests-rewind
